### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by TheRealM18** [Fexcraft/FVTM#12]
In the Version FVTM-2.6.b27-1.12.x.jar the server is asking for tough as nails, as it is missing an api call from this.  Could you fix this bug asap.

**Comment by Fexcraft** [comment]
Log?

**Comment by Fexcraft** [comment]
Log?

**Comment by TheRealM18** [comment]
[latest.log](https://github.com/Fexcraft/FVTM/files/2042054/latest.log)

**Comment by TheRealM18** [comment]
[crash-2018-05-26_20.59.51-server.txt](https://github.com/Fexcraft/FVTM/files/2042454/crash-2018-05-26_20.59.51-server.txt)
