### ISSUE TITLE
Missing pages in Medium containers

### ISSUE THREAD

**Issue by TheRealM18** [Fexcraft/FVTM#14]
in the past couple of version and current if you brake the cargo containers with a pickaxe it drops 2 items.  one is the block of the block you just broke, which ends up to get a missing page, and the rest of the container.

to reproduces this bug have a lot of different items in the container and you will see that the pages and items shift around. make sure your in survival though, as it is only survival bug

**Comment by Fexcraft** [comment]
Do you mean with "missing page", the black/purple square texture?

**Comment by TheRealM18** [comment]
no in the container itself

**Comment by TheRealM18** [comment]
http://prntscr.com/jponad

**Comment by Fexcraft** [comment]
Tested just now myself, ye, that shouldn't be dropping.
I'll see about fixing it.

**Comment by Fexcraft** [comment]
https://github.com/Fexcraft/FVTM/commit/523567fdce58c7e66da0c31faa992a4d1add8ca5 (<- fix)
Will be out next update, anything else related to that?
