### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by CAPTAINGAMER105** [Fexcraft/FVTM#15]
The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events

**Comment by Fexcraft** [comment]
Rest of the error? (e.g. log file / pastebin)

**Comment by CAPTAINGAMER105** [comment]
[crash-2018-06-10_14.26.36-client.txt](https://github.com/Fexcraft/FVTM/files/2088170/crash-2018-06-10_14.26.36-client.txt)
theres that

**Comment by Fexcraft** [comment]
I suppose this happens in the ConstuctorController GUI?

Which vehicle did you have in the constructor at that time?
_(There is also a newer FVTM version available btw.)_

**Comment by CAPTAINGAMER105** [comment]
nothing

**Comment by CAPTAINGAMER105** [comment]
I cant find anything for the ConstuctorController GUI

**Comment by Fexcraft** [comment]
No vehicles in the mod?

**Comment by CAPTAINGAMER105** [comment]
yeah and I tried putting addons in the addon folder C:\Users\User\Documents\Curse\Minecraft\Instances\modern craft\addons

**Comment by Fexcraft** [comment]
Hmm, I'd say, try first to update, as the log tells you have `b28`, while the latest is `b29`.
http://fexcraft.net/temp/fvtm_2.6.b29/ <- by coincidence part of the files is there temporarily.

May be that you downloaded a pack which is compiled for the newer version.
~~there is also that that I didn't put the latest version on curseforge~~

edit; updated FVTM on curseforge

**Comment by CAPTAINGAMER105** [comment]
it worked
