### ISSUE TITLE
Two crashes while launching the game

### ISSUE THREAD

**Issue by SuspiciousMango** [Fexcraft/FVTM#16]
I got this crash report loading a 1.12.2 modpack of mine for the first time without any addons. Something to do with Jurassicraft as well (Jurassicraft ver. 2.1.7 and FVTM ver. 2.6.b29):

[crash-2018-06-23_16.00.09-client.txt](https://github.com/Fexcraft/FVTM/files/2130197/crash-2018-06-23_16.00.09-client.txt)

Wondering if it was an issue with not including any addons, I added the 4 addons linked on the curse page (GEP ver. 1.6, FVP ver. 1.14, ZMP ver. 1.1, and HCP ver. 1.4) and got this crash:

[crash-2018-06-23_16.05.02-client.txt](https://github.com/Fexcraft/FVTM/files/2130198/crash-2018-06-23_16.05.02-client.txt)

**Comment by Fexcraft** [comment]
Both FCL and FVTM seem to be outdated.

Also yes, it won't work without at least GEP in the addons folder.

**Comment by SuspiciousMango** [comment]
I see. I grabbed the most recent files on curseforge which were not the most recent version. I updated to the current versions (FVTM 2.7.b30 and FCL XII.41) and got this crash: 

[crash-2018-06-24_10.26.43-client.txt](https://github.com/Fexcraft/FVTM/files/2130862/crash-2018-06-24_10.26.43-client.txt)

**Comment by Fexcraft** [comment]
Oh well, that's at least a new error, I'll see about it when I get time.

**Comment by Fexcraft** [comment]
1. ZMP wasn't officially yet updated to latest FVTM, here a file though which should work
[ZMP 1.1B](https://github.com/Fexcraft/FVTM/files/2109171/ZMP-V1.1b-1.12.x.zip)

2. I see now the latest FVP download is wrongly marked as 1.5.3, instead of 1.15.3, which is the latest version. (you have 1.14(?)),
Should be `fixed`.
