### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by halothanexiii** [Fexcraft/FVTM#17]
I have an odd crash that I can't seem to resolve on my own- it seems that every other part of FVTM is working, yet when I put FVP into my addons folder, I can't get past startup.
My forge is version 1.12.2-14.23.4.2738
FVTM is 2.7.b30
FCL is XII.41
GEP is 1.6
FVP is 1.9

Here is my crash report:
https://pastebin.com/KhSBd3MX

[I'm also running optifine and mr.crayfishs furniture mod but I don't think they're causing issues]

**Comment by Fexcraft** [comment]
FVP 1.15.3 ist latest IIRC.

**Comment by halothanexiii** [comment]
OH. I knew it was something small like that, hahah, thanks for putting up with me ;)
