### ISSUE TITLE
Game Crashes everytimme I hover over an assembled vehicle.

### ISSUE THREAD

**Issue by Geric2004** [Fexcraft/FVTM#2]
https://pastebin.com/T8cT3kpc

**Comment by Fexcraft** [comment]
The code seems to have changed... and I'm not sure anymore what was at that line.

But, GEP (General Essentials Pack) should go into the `addons` folder.
`FML has found a non-mod file General Essentials Pack-1.4 - for FVTM-1.12.2.jar in your mods directory.`

Try again with GEP in the addons folder.
