### ISSUE TITLE
Issue with derfl007's Road Mod

### ISSUE THREAD

**Issue by Dawn7293** [Fexcraft/FVTM#23]
Here is the issue: when the player his driving the car, it breaks the roads blocks under it, which is really problematic. Actually, I tried with a C1 but it is maybe related to all vehicles, on Minecraft 1.12.2.
![2018-09-19_23 10 38](https://user-images.githubusercontent.com/43421031/45781892-a1f77980-bc61-11e8-8321-8729ee379a95.png)

**Comment by Fexcraft** [comment]
That's Flansmod, isn't it?

FVTM is an independent mod, and FVTM does not break blocks (at least not yet).

You seem to have the FVP-Flansmod version installed.

**Comment by Fexcraft** [comment]
Try using this command though
`/teams vehiclesBreakBlocks false`
http://flansmod.com/teams-tutorial
