### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by BSKCorp** [Fexcraft/FVTM#24]
Forge 1.12.2 -14.23.4.2760
FVTM 2.7.32
GEP 1.6.2
FCL XII.43

Crash Log - https://pastebin.com/ARhYaSwZ

Crashed two times before with the HCP and FVP Pack as well.
All Mods and Addons where in the Mods folder. No Addon Folder had been or was created.

**Comment by Fexcraft** [comment]
https://github.com/Fexcraft/FVTM/issues/21
Try the file there.

**Comment by Fexcraft** [comment]
Known issue, but I'm stuck at some piece of code before I could release the new version, the file I mentioned is a patched version of the last release which so far worked for most/all people.

**Comment by BSKCorp** [comment]
Ok will give it a go. Thanks for the quick reply.

**Comment by BSKCorp** [comment]
Still crashes - https://pastebin.com/eHcTdnFZ

**Comment by Fexcraft** [comment]
You do not seem to have GEP installed.

**Comment by BSKCorp** [comment]
Well that was dumb of me, I thought I had grabbed them all in the mod folder. Well it did start up this time lol. But made a flat world in creative, went through the tabs. When clicking on the pre-made vehicles. it crashed. - https://pastebin.com/Nrv9AxSs that is the report for that one. tried again and got into the containers section. All the items had missing textures in the GUI and after a moment it crashed as well. - https://pastebin.com/QL1Cb7z1. If I knew more about java I would help figure out a fix or what have you. I would. This mod seems like it would be really really great! XD

**Comment by Fexcraft** [comment]
Both crashes seem to be the same, as I found out from examining a log related to #25 it seems that Forge doesn't load in the Addon's resources as I expected, a [quickfix file which fixes the crashing is here](https://cdn.discordapp.com/attachments/365125356660719638/495544728251793408/FVTM-2.7.33pre-1.12.x.jar).

For the textures/resources to load properly, try to put the addon files into the `<minecraft dir>/addons ` folder.
I'll see about forcing the Addon resources to get loaded in, I could send you test files if you would join the discord server(faster) or better stay on github?

edit: test file https://cdn.discordapp.com/attachments/365126848914391040/496010926785429514/FVTM-2.7.33pre2-1.12.x.jar

**Comment by Fexcraft** [comment]
Tried it on a normal client and it seems to work well.

**Edit:** Released version 2.8.33, which should fix some of the reported issues.

**Comment by Fexcraft** [comment]
Should be fixed in 2.8.33
