### ISSUE TITLE
Updated this mod, crashing upon startup

### ISSUE THREAD

**Issue by CelestialDiablo** [Fexcraft/FVTM#26]
I just updated this mod today (12/2/18 3:10 PM CST (CDT)) and the game crashes upon clicking the play button.

The launcher tells me the game crashed whilst Initializing game.

I get an error that looks like this...

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/fexcraft/mod/lib/api/network/IPacketListener

I know that it is this mod causing issues because I took it out of the mods folder, launched the game, the game loaded everything else perfectly and went to the main menu.

Crashlog: [crash-2018-12-02_16.15.08-client.txt](https://github.com/Fexcraft/FVTM/files/2637487/crash-2018-12-02_16.15.08-client.txt)

Thanks in advance,

CelestialDiablo

**Comment by Fexcraft** [comment]
FVTM wasn't updated (released) for FCL 1.XII.44 yet.
Use FCL XII.43 till next update.

**Comment by CelestialDiablo** [comment]
Oh, Ok, that makes sense, thank you

**Comment by CelestialDiablo** [comment]
One more thing, I also had to revert FSMM to one version back, it was causing the game to crash even after putting FCL back to XII.43

Update on this: it still crashes, I think the game hates me, I'll try again in a month or two when the mods are updated.

**Comment by Fexcraft** [comment]
Well yes, FSMM, States, (and I think FRSM?) were updated to latest FCL,
(as such if downgrading FCL, those also need to be downgraded)
FVTM was not, as I'm still working on converting to the new model format.
FVTM will be released with FCL 1.XII.45  (most probably).

What's the new crash?

**Comment by Fexcraft** [comment]
New version of FVTM has been posted, it needs FCL XII.45 to run.
