### ISSUE TITLE
Game Crashes One at 3 of 7% Loaded Complete

### ISSUE THREAD

**Issue by win10Device** [Fexcraft/FVTM#28]
This is the Crash report: 
Note The mods That are not Flex mod are disable as seen here:
![Screenshot (44)](https://user-images.githubusercontent.com/44788187/63156735-b05c3a00-c058-11e9-9481-70b70ce10781.png)

**Comment by Fexcraft** [comment]
I do not see a single of my mods in that log, especially not FVTM.

**Comment by win10Device** [comment]
Oh Sorry wrong crash report, This is the Crash report:
[crash-2019-08-16_18.55.04-client.txt](https://github.com/Fexcraft/FVTM/files/3511353/crash-2019-08-16_18.55.04-client.txt)

**Comment by Fexcraft** [comment]
Your fcl version is far too old, get XII.45 for latest FVTM.

**Comment by win10Device** [comment]
I Know But The Latest version of FCL Curses My Game To Get error on load making the game Crash
I've tried using a older version of fvtm but that got a error too

**Comment by Fexcraft** [comment]
I said 45 though, not latest (46), it is known that one won't work.

Although other mods will require 46, so it won't be compatible till next FVTM update.

**Comment by win10Device** [comment]
Oh OK What do I use then of FCL and FVTM,
NOTE: I don't have My Laptop for a month so I can't use it
I can In a Month

**Comment by Fexcraft** [comment]
FCL XII.45 with FVTM 2.9.35

Although, in a month... maybe FVTM 3 will be already out.
It will be working with latest FCL, no issues there.

**Comment by win10Device** [comment]
This Issue Is still a problem
Can you Please can you reopen this Issue because I told you before My laptop Is Not working Currently
in this Comment:
" NOTE: I don't have My Laptop for a month so I can't use it
I can In a Month"
OK? So we both have to wait For me to get my laptop back so I can Try The Mods
Just in case that I have more Issues!

**Comment by Fexcraft** [comment]
It is a common error that people take 46 with fvtm instead of 45, so far any case where the correct version was used, solved the issues.

**Comment by win10Device** [comment]
I did use 45 And I did do it,
It Could be My Forge Version Because I have had Mods That Want Start Because Of the Forge Version
Mods + Some forge Versions Causes A Crash
My Forge Version Is:  1.12.2-14.23.5.2808

**Comment by win10Device** [comment]
If You Test using your mod on Forge 1.12.2-14.23.5.2808
I can't Change My Forge Version Because All My Mods In My Mods Set Will All crash Because That Can't Handle Forge Down/Upgrade!

**Comment by Fexcraft** [comment]
Well, by now FVTM 3 is out, try that one. (needs latest fcl)

**Comment by win10Device** [comment]
I don't get my Laptop back till the 16-9-2019 Australian Eastern Standard Time
And My Laptop is not on the Internet By My table Is connected,
So What I do is connect My table by USB to my laptop and Download The mods then Transfer the files to my laptop

**Comment by win10Device** [comment]
FVTM 3 Has fix the "Crashing Bug"
So it Fixed
