### ISSUE TITLE
chat blocked in single player

### ISSUE THREAD

**Issue by malthenon** [Fexcraft/FVTM#29]
As stated in the title, My game wont allow me to use the chat in single player. Luckily, I have vanillaFix installed so it spit out an error file despite there not being a crash. From what i can see, it is breaking at line 224 in the PlayerEvents file, caused by the onMessage function.
[crash-2019-08-18_16.28.04-server.txt](https://github.com/Fexcraft/FVTM/files/3513585/crash-2019-08-18_16.28.04-server.txt)

**Comment by Fexcraft** [comment]
I think you are at the wrong repository.

**Comment by malthenon** [comment]
That I am. appologies, I'll post this in the states repo.
