### ISSUE TITLE
Destruction of construction center and getting the vehicle off of it

### ISSUE THREAD

**Issue by wojciechgib** [Fexcraft/FVTM#30]
Minecraft version: 1.11.2
Mod version: : 1.0-alpha10
What is the problem:
I have 2 problems:
1. I can not destroy the constructor centre display (Photo Below). Is it destructible at all, if so how can I do it?

![Screenshot_47](https://user-images.githubusercontent.com/54496409/63647767-7b21ad00-c726-11e9-8312-2f1f8c1e9f0d.png)

2. I tried getting a vehicle off the constructor centre display but I can not, I tried hitting it and tried getting in but I do not know how to enter it. Any keyboard buttons combination?

Thanks!

**Comment by Fexcraft** [comment]
The 1.11.2 version is long discontinued. ~~Also it was called FVM, not FVTM.~~

**Comment by Fexcraft** [comment]
As far I recall, or at least how it always worked in FVTM,
the vehicle is usually stored inside the _Constructor Controller_, not the center.

**Comment by wojciechgib** [comment]
Thanks, @Fexcraft , can you please point me where I could find binaries for the most recent version of this mod?

**Comment by Fexcraft** [comment]
Where did you find the ones you used?
I usually either post my mods on CurseForge or Fexcraft.Net

The latest available version is 2.9.35, the required FCL version for it is XII.45.

Currently I'm rewritting FVTM into the version 3.0.0, it will contain many new 
features and other fancy things (improvements over version 2.x).
It will be compatible with latest FCL.

For development details you can join our discord Server.
