### ISSUE TITLE
Crash by Pick Rail in Inventory of Player

### ISSUE THREAD

**Issue by Titoo8899** [Fexcraft/FVTM#31]
Hi,
then I pick from your mod the Rail of Creative Tab in your Inventory the game Freeze and Crash. Test by newest Versions.

**Comment by Fexcraft** [comment]
:thinking:

**Comment by Fexcraft** [comment]
Does it happen from the item alone or when hovering/tooltip?
Does it happen when getting from /give?

**Comment by Titoo8899** [comment]
hi,
only then it place in inventory

**Comment by Fexcraft** [comment]
Is this still an issue in the latest version?
