### ISSUE TITLE
Emergency vehicles

### ISSUE THREAD

**Issue by daniv1205** [Fexcraft/FVTM#36]
Will emergency vehicles be added in a future update? I mean ambulance, fire truck and police car

**Comment by Fexcraft** [comment]
Solely depends on if someone makes them.

This is a mod that provides the ability to made addon packs,
and all vehicles so far are part of addon packs.

**Comment by Fexcraft** [comment]
If you want to try out modelling or pack making, currently I'm preparing a few video tutorials on that.
