### ISSUE TITLE
[Forge 14.23.1.2581] "java.lang.NullPointerException: Rendering screen" when entering Controls menu.

### ISSUE THREAD

**Issue by Ksehn** [Fexcraft/FVTM#4]
Hi,

I'm using FVTM-2.2-alpha17 (with DEP-Fexcraft Common Library-XII.34) on Forge 14.23.1.2581 (for 1.12.2), and everytimes I try to access the controls menu, the game crash with the following crash report: https://pastebin.com/raw/Zbw9QRwd

Also, thanks for creating this mod ^-^ !

**Comment by Fexcraft** [comment]
I'm currently having the issue aswel, and I'm pretty unsure on it's origin. Yet.
- - - - - - - -
I found the error, will be fixed next release.
![image](https://user-images.githubusercontent.com/11726534/34319838-13750758-e7ec-11e7-8e32-8dfe516a68eb.png)

**Comment by Ksehn** [comment]
That was quick, thanks ! I will try this when the next update will be released on Curseforge.

Thanks again o/

**Comment by Ksehn** [comment]
Everything works 👍
