### ISSUE TITLE
NBT tag too large

### ISSUE THREAD

**Issue by NicodemusN** [Fexcraft/FVTM#46]
Hi! There seems to be a problem with making larger roads with FVTM on a server. The problem does not occure when I make larger road segments with fewer points, but when I try to make a bigger turning one, it gives this error and throws me out. I'm able to rejoin the server only after deleting the server's world file's "playerdata" folder.
![Screen Capture_select-area_20220827180714](https://user-images.githubusercontent.com/87670335/187065357-53750ea2-f530-4256-ba78-1260ff79ac4d.png)

I have not encountered this issue on singleplayer, only multiplayer. I use other mods too, but I don't see a way for them to interact with the road tool.
Forge: 1.12.2-14.23.5.2860
Fex's mod version: FVTM-3.7.65d

**Comment by Fexcraft** [comment]
It could be the undo cache being too big, as it's currently saved per-item.

**Comment by NicodemusN** [comment]
Is it something that you would be able to fix in the mod code or can I as the server owner do something about it?

**Comment by Fexcraft** [comment]
I'll have to move the cache elsewhere.

**Comment by Fexcraft** [comment]
[FVTM-3.8.69_pre.jar.zip](https://github.com/Fexcraft/FVTM/files/9439580/FVTM-3.8.69_pre.jar.zip)
Try this (note it's a zipped jar, you have to unpack it).
I also extended the undo cache to up to 10 entries.

**Comment by NicodemusN** [comment]
Hey! After updating to that version, my client won't start. It crashes everytime when forge starts constructing your mod.
Here is my log of the crash: https://pastebin.com/qgLCJxiz

**Comment by Fexcraft** [comment]
It is unrelated to the earlier issue 🤔 
I'll look into it.

**Comment by Fexcraft** [comment]
Update FCL and GEP.
