### ISSUE TITLE
when im really far away from spawn, the road tool breaks

### ISSUE THREAD

**Issue by steiger9350** [Fexcraft/FVTM#50]
so when im like 8 million blocks away from spawn, the road tool breaks. the lines mess up, when it creates the road its all off and the lines are broken too when placed.

**Comment by Fexcraft** [comment]
Could you give more info on how it happened?

**Comment by steiger9350** [comment]
ill send a video or photo, its like normal at spawn. at spawn it works like how it should work. but at 8 million blocks away from spawn, it messes up. is this a bug or a minecraft thing

**Comment by steiger9350** [comment]
![Screenshot_20230129_023411](https://user-images.githubusercontent.com/99939646/215352022-d316bec2-5240-430b-b452-57472b0b0fc7.png)

**Comment by Fexcraft** [comment]
Are you sure there isn't a marker at spawn?

**Comment by steiger9350** [comment]
at spawn its totally normal
![Screenshot_20230129_030121](https://user-images.githubusercontent.com/99939646/215352753-7e497ce8-1647-45e5-932c-ac33cd598153.png)
![Screenshot_20230129_030209](https://user-images.githubusercontent.com/99939646/215352758-31d73636-6b52-46f1-bf3c-0136f9c140af.png)

**Comment by Fexcraft** [comment]
Side note: please use the auto-connecting (cross form) line markers

I'll see if I get this issue too on 8m blocks away.

**Comment by Fexcraft** [comment]
Ok. I'm getting the same result.

**Comment by steiger9350** [comment]
must be a bug, not with cubic chunks or terra plus plus..

**Comment by Fexcraft** [comment]
Actually a lot more than the preview seems to be breaking.

Do you _have to_ build that far away?

**Comment by steiger9350** [comment]
yea, im trying to build my real area with terra plus plus. it creates the world in 1:1, you spawn at the middle of the ocean. i wonder where it starts to break?

**Comment by Fexcraft** [comment]
From testing from 8m backwards, it's almost fine at 80k-50k but jittering, 10k is almost fine.

**Comment by Fexcraft** [comment]
![image](https://user-images.githubusercontent.com/11726534/215354162-bd3184e9-1216-4f6f-801d-7b1cfc8b0a8d.png)
Rails are also broken, so I have general guesses where to look.

**Comment by steiger9350** [comment]
wow, i can't believe that people never noticed this. i have been trying to figure out how to use the immersive vehicle road building system but i can't find any info on it online. says in the manual that they exist, so i don't know.

**Comment by Fexcraft** [comment]
Immersive Vehicles is another mod, I don't know the status of their road systems. Last I recall they have not been block based.

**Comment by steiger9350** [comment]
hmm alright, something has to be causing this bug. if its a minecraft thing, oh well.

**Comment by Fexcraft** [comment]
This might be related to floating point inaccuracy on both java and gpu side, at least looks so from testing.
(Like for example there is many things that render fine, and vehicles render fine too if toggling the config setting for them being rendered separately, so something _might_ go wrong on the other render calls.
On another quick test of a modification the preview didn't jitter but was still a zig-zag.)
Will have to see what fixes this and what can be done.

**Comment by steiger9350** [comment]
okay. but when it places the road, its a bit messed up. lines tend to be broken, not placing at all. i don't know if that has to relate to the rendering problem.

**Comment by Fexcraft** [comment]
It could be related to the accuracy problem, I use _float_ number type, which usually is completely fine, but perhaps it breaks in situations like this? Other things in minecraft use _double_ (number type) and appear fine.
(float is kinda more lightweight but has downsides in situations like these.)

**Comment by steiger9350** [comment]
how is it going? is it working now? or you took a break? java is hard, so i could see that.

**Comment by Fexcraft** [comment]
It's night in this timezone.

**Comment by steiger9350** [comment]
but does the road place normally? looks like you fixed the rendering, but my roads don't really place right before

**Comment by Fexcraft** [comment]
The issue involved everything that used a separate render pass, I was so far able to quick-fix everything except rails and roads.
Those need a bit more work and testing, might not be able to finish today.

**Comment by steiger9350** [comment]
how is it going? good? or not good?

**Comment by Fexcraft** [comment]
Slow, implementing solutions that need larger reworks.

**Comment by steiger9350** [comment]
alright alright, no pressure. work as much as you can or need.

**Comment by Fexcraft** [comment]
![img0](https://cdn.discordapp.com/attachments/365126848914391040/1070762993555619941/image.png)
![img1](https://cdn.discordapp.com/attachments/365126848914391040/1070763039692968056/image.png)
Still have to modify rails and control if nothing broke on the conversion.

Preview itself works well.
![img2](https://cdn.discordapp.com/attachments/365126848914391040/1070763576500953149/image.png)

**Comment by steiger9350** [comment]
can the road curve without breaking? also how about lines? do they not mess up now? but still, great progress

**Comment by Fexcraft** [comment]
I can send you a test version on discord if you want (the link to it is in description),
because I'm still checking and fixing the rail system, and until then I can't release an update.
Roads seem to work ok.

**Comment by steiger9350** [comment]
okay, ill test it out and see how it goes. i really needed the roads, thanks for the fix

**Comment by Fexcraft** [comment]
Changes will be available next update/release.
Fixed prerelease available on discord.
