### ISSUE TITLE
The game crashed whilst rendering block entity AdjustableWheelAttribute

### ISSUE THREAD

**Issue by Stiller90** [Fexcraft/FVTM#6]
I've been trying to get this thing to work, and it crashes from loading a block entity.

[crash-2018-03-16_16.03.53-client.txt](https://github.com/Fexcraft/FVTM/files/1820662/crash-2018-03-16_16.03.53-client.txt)

Click the link to see the report.

**Comment by Fexcraft** [comment]
Please update the Addon packs, the class it can't find doesn't exists in latest FVTM/GEP.
So at least FVP is outdated.

**Comment by Stiller90** [comment]
I'll see what I can do.
