### ISSUE TITLE
Game crashed when i enter in a car

### ISSUE THREAD

**Issue by Twelfh** [Fexcraft/FVTM#7]
Hello ,I have a problem with FVTM .Everytime I enter into a car ,the game crashes .I don't know why it does that and I tried a lot of things: take an old version from the mod ,remove all my mods...Do someone know what's going on?Thanks in advance (sorry for my bad english ,I'm french )Here's the crash log : 
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 3/18/18 7:40 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: 316
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.fexcraft.mod.fvtm.gui.GuiVehicleController.isKeyDown(GuiVehicleController.java:190)
	at net.fexcraft.mod.fvtm.gui.GuiVehicleController.func_146269_k(GuiVehicleController.java:154)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.DirectByteBuffer.get(Unknown Source)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at net.fexcraft.mod.fvtm.gui.GuiVehicleController.isKeyDown(GuiVehicleController.java:190)
	at net.fexcraft.mod.fvtm.gui.GuiVehicleController.func_146269_k(GuiVehicleController.java:154)

-- Affected screen --
Details:
	Screen name: net.fexcraft.mod.fvtm.gui.GuiVehicleController

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Twelfh'/58, l='MpServer', x=-831.92, y=4.08, z=847.20]]
	Chunk stats: MultiplayerChunkCache: 419, 419
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1088,4,876), Chunk: (at 0,0,12 in -68,54; contains blocks -1088,0,864 to -1073,255,879), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Level time: 27375 game time, 27375 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 73 total; [EntitySlime['Slime'/128, l='MpServer', x=-812.37, y=4.00, z=835.50], EntitySheep['Mouton'/129, l='MpServer', x=-789.55, y=4.00, z=828.79], EntityChicken['Poule'/130, l='MpServer', x=-796.77, y=4.00, z=826.85], EntityCow['Vache'/7, l='MpServer', x=-911.48, y=4.00, z=860.74], EntityPig['Cochon'/136, l='MpServer', x=-753.67, y=4.00, z=925.54], EntitySheep['Mouton'/137, l='MpServer', x=-762.76, y=4.00, z=925.67], EntitySlime['Slime'/138, l='MpServer', x=-823.39, y=4.00, z=811.90], EntitySheep['Mouton'/17, l='MpServer', x=-902.65, y=4.00, z=830.82], EntitySheep['Mouton'/18, l='MpServer', x=-907.85, y=4.00, z=853.61], EntitySheep['Mouton'/146, l='MpServer', x=-773.31, y=4.00, z=921.79], EntityCow['Vache'/19, l='MpServer', x=-905.98, y=4.00, z=852.95], EntityHorse['Cheval'/20, l='MpServer', x=-909.37, y=4.00, z=859.86], EntitySheep['Mouton'/148, l='MpServer', x=-826.71, y=4.00, z=822.00], EntitySlime['Slime'/21, l='MpServer', x=-901.56, y=4.00, z=851.03], EntitySlime['Slime'/149, l='MpServer', x=-824.05, y=4.08, z=810.38], EntityChicken['Poule'/22, l='MpServer', x=-899.50, y=4.00, z=909.50], EntitySlime['Slime'/150, l='MpServer', x=-817.88, y=4.00, z=822.11], EntityChicken['Poule'/23, l='MpServer', x=-899.50, y=4.00, z=905.50], EntityHorse['Cheval'/24, l='MpServer', x=-910.74, y=4.00, z=920.63], EntityHorse['Cheval'/25, l='MpServer', x=-910.99, y=4.00, z=919.01], EntitySheep['Mouton'/41, l='MpServer', x=-891.64, y=4.00, z=834.89], EntityCow['Vache'/42, l='MpServer', x=-881.50, y=4.00, z=910.50], EntitySlime['Slime'/43, l='MpServer', x=-889.52, y=4.92, z=891.09], EntityVillager['Villageois'/49, l='MpServer', x=-782.70, y=7.00, z=861.70], SeatEntity['entity.fvtm:seat.name'/177, l='MpServer', x=-831.92, y=4.58, z=847.20], EntityVillager['Villageois'/50, l='MpServer', x=-782.70, y=5.00, z=855.30], SeatEntity['entity.fvtm:seat.name'/178, l='MpServer', x=-830.99, y=4.58, z=847.56], EntityVillager['Villageois'/51, l='MpServer', x=-782.87, y=5.00, z=848.38], SeatEntity['entity.fvtm:seat.name'/179, l='MpServer', x=-832.37, y=4.58, z=848.37], EntityVillager['Villageois'/52, l='MpServer', x=-783.71, y=5.00, z=848.99], SeatEntity['entity.fvtm:seat.name'/180, l='MpServer', x=-831.44, y=4.58, z=848.73], EntityVillager['Villageois'/53, l='MpServer', x=-778.85, y=5.00, z=846.84], SeatEntity['entity.fvtm:seat.name'/181, l='MpServer', x=-831.90, y=4.58, z=848.55], EntityVillager['Villageois'/54, l='MpServer', x=-779.36, y=5.00, z=847.70], WheelEntity['entity.fvtm:wheel.name'/182, l='MpServer', x=-833.14, y=4.00, z=848.98], EntityVillager['Villageois'/55, l='MpServer', x=-781.70, y=5.00, z=883.46], WheelEntity['entity.fvtm:wheel.name'/183, l='MpServer', x=-831.27, y=4.00, z=849.70], WheelEntity['entity.fvtm:wheel.name'/184, l='MpServer', x=-829.86, y=4.00, z=846.02], WheelEntity['entity.fvtm:wheel.name'/185, l='MpServer', x=-831.73, y=4.00, z=845.30], EntitySlime['Slime'/59, l='MpServer', x=-819.60, y=4.00, z=841.36], LandVehicleEntity['C7'/62, l='MpServer', x=-831.50, y=4.33, z=847.50], EntitySlime['Slime'/72, l='MpServer', x=-821.78, y=4.27, z=829.94], EntitySlime['Slime'/73, l='MpServer', x=-854.58, y=5.17, z=919.24], EntityCow['Vache'/74, l='MpServer', x=-845.85, y=4.00, z=890.34], EntityChicken['Poule'/75, l='MpServer', x=-879.50, y=4.00, z=908.50], EntityChicken['Poule'/76, l='MpServer', x=-875.04, y=4.00, z=907.41], EntityCow['Vache'/77, l='MpServer', x=-871.47, y=4.00, z=900.02], EntityItem['item.item.bone'/78, l='MpServer', x=-854.02, y=4.00, z=849.94], EntitySlime['Slime'/79, l='MpServer', x=-868.35, y=4.00, z=829.47], EntitySlime['Slime'/80, l='MpServer', x=-879.13, y=4.00, z=844.35], EntitySlime['Slime'/81, l='MpServer', x=-876.22, y=4.95, z=854.07], EntitySlime['Slime'/83, l='MpServer', x=-868.59, y=4.42, z=792.00], EntityPlayerSP['Twelfh'/58, l='MpServer', x=-831.92, y=4.08, z=847.20], CameraEntity['inconnu'/87, l='MpServer', x=-831.50, y=4.33, z=847.50], EntitySkeleton['Squelette'/93, l='MpServer', x=-818.48, y=4.00, z=872.25], EntitySlime['Slime'/94, l='MpServer', x=-806.95, y=4.67, z=847.54], EntitySlime['Slime'/95, l='MpServer', x=-798.18, y=4.00, z=846.69], EntitySlime['Slime'/96, l='MpServer', x=-815.93, y=4.52, z=846.21], EntityChicken['Poule'/97, l='MpServer', x=-804.86, y=4.00, z=908.86], EntityItem['item.item.egg'/98, l='MpServer', x=-804.98, y=4.00, z=909.73], EntityChicken['Poule'/99, l='MpServer', x=-784.79, y=3.94, z=851.48], EntityItem['item.item.egg'/100, l='MpServer', x=-784.85, y=4.00, z=842.13], EntityVillager['Villageois'/101, l='MpServer', x=-784.70, y=5.00, z=848.73], EntitySlime['Slime'/103, l='MpServer', x=-836.49, y=4.00, z=903.99], EntitySlime['Slime'/231, l='MpServer', x=-832.10, y=4.00, z=822.19], EntitySlime['Slime'/105, l='MpServer', x=-835.63, y=4.00, z=911.94], EntitySlime['Slime'/106, l='MpServer', x=-826.16, y=5.08, z=873.45], EntityCow['Vache'/108, l='MpServer', x=-844.22, y=4.00, z=849.56], EntitySlime['Slime'/112, l='MpServer', x=-802.61, y=4.34, z=829.08], EntitySlime['Slime'/113, l='MpServer', x=-810.43, y=4.72, z=813.10], EntitySlime['Slime'/120, l='MpServer', x=-838.11, y=4.00, z=864.92], EntityChicken['Poule'/123, l='MpServer', x=-825.92, y=4.00, z=855.15], EntitySlime['Slime'/125, l='MpServer', x=-823.33, y=4.52, z=847.54]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 520790760 bytes (496 MB) / 1321205760 bytes (1260 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 4 total; -XX:+UseG1GC -XX:ConcGCThreads=4 -Xmx6144M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2621 Optifine OptiFine_1.12.2_HD_U_C9 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                             | Signature                                |
	|:--------- |:----------------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                      | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                      | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.2.2621.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.2.2621 | forge-1.12.2-14.23.2.2621.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar        | None                                     |
	| UCHIJAAAA | fcl               | XII.34       | Fexcraft+Common+Library-XII.35.jar | None                                     |
	| UCHIJAAAA | fvtm              | 2.3-b21      | FVTM-2.3-b21-1.12.x.jar            | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 6300M Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2621
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 6300M Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU M 380 @ 2.53GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 10
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
	OpenGlRenderer: AMD Radeon HD 6300M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Fexcraft** [comment]
It's passing a key number which is larger then the amount of keys in the Keyboard.class
Do you have any custom keybinds?
*`edit`* What's the "Engine Toggle" keybind set to?

I'll try to fix this next version.

**Comment by Twelfh** [comment]
It was set to "<" .I reset all the keys and it works ! Thanks :D
