### ISSUE TITLE
Vehicles not showing at all

### ISSUE THREAD

**Issue by tylerdep** [Fexcraft/FVTM#8]
In the creative menu none of the vehicles are there but the Minecraft completely launches
Plz help im going over a friends house this weekend and this would really be grate if the mod would be working, im not 100% saying its a code problem, i just think i did something wrong, bc i couldnt find anyone else with this problem
![screen shot 2018-04-10 at 12 37 41 pm](https://user-images.githubusercontent.com/38257956/38570512-05ba51c0-3cbc-11e8-9bdb-20c92c6ee3a2.png)
![screen shot 2018-04-10 at 12 39 32 pm](https://user-images.githubusercontent.com/38257956/38570726-867be940-3cbc-11e8-8b0f-3bb2240b14dd.png)
![screen shot 2018-04-10 at 12 40 55 pm](https://user-images.githubusercontent.com/38257956/38570729-86ab0f18-3cbc-11e8-8c09-77774d14e9f4.png)
![Uploading Screen Shot 2018-04-10 at 12.41.00 PM.png…]()
![Uploading Screen Shot 2018-04-10 at 12.41.03 PM.png…]()
![Uploading Screen Shot 2018-04-10 at 12.41.05 PM.png…]()
![Uploading Screen Shot 2018-04-10 at 12.41.08 PM.png…]()
![Uploading Screen Shot 2018-04-10 at 12.41.11 PM.png…]()
![Uploading Screen Shot 2018-04-10 at 12.41.18 PM.png…]()
![Uploading Screen Shot 2018-04-10 at 12.41.25 PM.png…]()

**Comment by Fexcraft** [comment]
Make sure you have some "Addons", and that they are in the `/.minecraft/addons` folder.
Create it if it's missing.

(GEP is also an Addon)
